LOWERC_ROOT := Observation
UPPERC_ROOT := OBSERVATION

# Component fragments from */Makefile.inc
include $(LOWERC_ROOT)/Playback/Makefile.inc
include $(LOWERC_ROOT)/Recognizer/Makefile.inc
include $(LOWERC_ROOT)/Observer/Makefile.inc
