// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KinectInterp.proto

#ifndef PROTOBUF_KinectInterp_2eproto__INCLUDED
#define PROTOBUF_KinectInterp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_KinectInterp_2eproto();
void protobuf_AssignDesc_KinectInterp_2eproto();
void protobuf_ShutdownFile_KinectInterp_2eproto();

class KinectInterpProto;

// ===================================================================

class KinectInterpProto : public ::google::protobuf::Message {
 public:
  KinectInterpProto();
  virtual ~KinectInterpProto();
  
  KinectInterpProto(const KinectInterpProto& from);
  
  inline KinectInterpProto& operator=(const KinectInterpProto& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const KinectInterpProto& default_instance();
  
  void Swap(KinectInterpProto* other);
  
  // implements Message ----------------------------------------------
  
  KinectInterpProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KinectInterpProto& from);
  void MergeFrom(const KinectInterpProto& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:KinectInterpProto)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_KinectInterp_2eproto();
  friend void protobuf_AssignDesc_KinectInterp_2eproto();
  friend void protobuf_ShutdownFile_KinectInterp_2eproto();
  
  void InitAsDefaultInstance();
  static KinectInterpProto* default_instance_;
};
// ===================================================================


// ===================================================================

// KinectInterpProto

// required int64 id = 1;
inline bool KinectInterpProto::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void KinectInterpProto::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void KinectInterpProto::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void KinectInterpProto::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 KinectInterpProto::id() const {
  return id_;
}
inline void KinectInterpProto::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_KinectInterp_2eproto__INCLUDED
